apiVersion: v1
kind: Service
metadata:
  name: srv-8080-echo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: srv-8080-echo
    # green/blue deployment:
    version: v3
  type: LoadBalancer
